### PR TITLE
Fix olive/olives and goose/geese, with tests

### PR DESCRIPTION
**Pull request by HipsterJazzbo**
This will negate #39 as well.

### CODE REVIEW

**Comment by malarzm** [comment]
@HipsterJazzbo mind squashing commits?

**Comment by HipsterJazzbo** [comment]
@malarzm You should be able to squash and merge: https://github.com/blog/2141-squash-your-commits

**Comment by malarzm** [comment]
@HipsterJazzbo IIRC using that approach does not make a merge commit which we like to have :)

**Comment by garrettw** [comment]
Then what’s the point of making him squash his commits if you still want a merge commit? Seems like it’s just making a big deal about nothing, just being particular.

**Comment by malarzm** [comment]
> Then what’s the point of making him squash his commits

Because commit named "Fix tab" is useless, I'm fine with other two being here.

> Seems like it’s just making a big deal about nothing, just being particular.

We just care about the history :) Also, where I've made it a big deal?

**Comment by garrettw** [comment]
Oh yeah you’re right, “fix tab” is useless.

**Comment by HipsterJazzbo** [comment]
@malarzm Okay, should be good to go now :)

**Comment by malarzm** [comment]
Thank you @HipsterJazzbo!

**Comment by HipsterJazzbo** [comment]
@malarzm No problem :) Any plans on when it'll be tagged? I'm currently serving out shopping lists to people that tell them to buy "olifes" 😂

**Comment by malarzm** [comment]
I'll try to go through other open issues/PRs tomorrow and maybe cut a release by then

Re squash and merge: the description still sounds like it's doing fast-forward instead of a merge commit... I'll try to read this up or test on some dummy repository :)

**Pull request merged**
