### PR TITLE
Ensures that Tights, and Shorts and Blouse are single/pluralised properly

### PR DESCRIPTION
**Pull request by powellblyth**
Ensures that Tights, and Shorts are never singularised in English, ensures that Blouses is never singularised to Blice.

Previously, "Shorts" would singularise to "Short", but I still have "one pair of shorts" 
Previously, "Tights" would singularise to "Tight", but I still have "one pair of tights"
Previously, "Blouses" would singularise to "Blice", but that word is meaningless in english

### CODE REVIEW

**Comment by derrabus** [comment]
Can you please add your test cases to `EnglishFunctionalTest`?

**Comment by powellblyth** [comment]
> Can you please add your test cases to `EnglishFunctionalTest`?

Ah yes no problem. Sorry I didn’t find the best place to put those in. I’ll try and sort this tonight

**Comment by powellblyth** [comment]
Hi, I've added the tests.

I notice there's a LOT of duplicates.. e.g. Moose is in there 3 times.

Would you like a PR deduping these? Or am I missing something?

**Comment by derrabus** [comment]
> I notice there's a LOT of duplicates.. e.g. Moose is in there 3 times.

Looks like this happened in #101 (cc @jwage). From my point of view, all those duplicates do is causing the same test to be executed multiple times. I think, we can delete them.

**Pull request merged**
