### PR TITLE
Fix pluralization of 'work' and 'experience'

### LINKED ISSUE #153: "work" pluralizing as "work"
After updating from 1.3.1 to 1.4.1, my Laravel project is failing because it is pluralizing "work" to "work"

### PR DESCRIPTION
**Pull request by jochensengier**
Fixes #153

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send this to the 1.4 branch.

**Comment by SenseException** [comment]
As asked in https://github.com/doctrine/inflector/issues/153#issuecomment-628611022, please target the 1.4 branch.

**Comment by greg0ire** [comment]
I did it for you, now you know why you should commit directly on master, even if it is your fork :wink:

**Comment by greg0ire** [comment]
Thanks @jochensengier !

**Comment by jochensengier** [comment]
Oh shoot, sorry about that! 🤦‍♂️

**Comment by greg0ire** [comment]
No worries, I said that only because it might be confusing for you, but I rebase branches called master on numbered branches every day, really not a big deal :)

**Pull request merged**
