### PR TITLE
singular of 'avalanches' is 'avalanche', not 'avalanch'

### PR DESCRIPTION
**Pull request by jarednipper**

### CODE REVIEW

**Comment by seanbright** [comment]
I would put this at the front of the list to maintain the alphabetical ordering

**Comment by jarednipper** [comment]
This list wasn't alphabetized properly before I changed anything, but I moved the 'avalanches' entry to the start.

**Comment by seanbright** [comment]
Ah. You're right. Looks like when "oasis" was added it was just tacked on the end. My mistake.

**Comment by Ocramius** [comment]
Needs addition in the respective tests

**Comment by seanbright** [comment]
@Ocramius, done in #51

**Comment by Ocramius** [comment]
Duplicate of #51, thanks @seanbright!

**Pull request closed without merging**
