### PR TITLE
Update statement about legacy API deprecation/drop

### LINKED ISSUE #171: Documentation Depreciation Statement not Correct
The documentation for both 1.4.3 and for 2.0.3/2.1 both state:

> The API present in Inflector 1.x is still available, but will be deprecated in a future release and dropped for 3.0. Support for languages other than English is available in the 2.0 API only.

However this statement seems to have been written for the 1.x branch, and at a time at which removal was planned for a "3.0" release rather than 2.0.

Could the documentation for both releases be updated to clarify the reality of the situation, that the old API is deprecated as of 1.4.x, and is dropped in 2.0?

### PR DESCRIPTION
**Pull request by dotsam**
Fixes #171

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by SenseException** [comment]
@ostrolucky ping

**Comment by ostrolucky** [comment]
I can't hit merge here either.

> Coding Standards (7.4) Expected — Waiting for status to be reported

**Comment by greg0ire** [comment]
Let's rebase then.

**Comment by greg0ire** [comment]
This should fix it: https://github.com/doctrine/inflector/pull/177

**Comment by greg0ire** [comment]
Thanks @dotsam !

**Pull request merged**
