### PR TITLE
add 'epoch' to irregular words list

### PR DESCRIPTION
**Pull request by kyosheek**
Add irregular word 'epoch' to list. Reference: https://www.britannica.com/dictionary/epoch

### CODE REVIEW

**Comment by greg0ire** [comment]
@kyosheek thanks for this. What was the behavior before your fix?

Cc @driesvints

**Comment by kyosheek** [comment]
@greg0ire it was according to grammar rules I suppose (I am not native speaker :d), `epoch -> epoches`, like with witch/witches, watch/watches etc.

**Comment by greg0ire** [comment]
> I suppose

What do you mean? You haven't seen an actual bug? How did you spot the issue?

**Comment by kyosheek** [comment]
I mean that pluralizes acts according to grammar rules, but the `epoch` word is exception in this case, sorry for the confusion.

The bug appeared in our production code while using Laravel's helper function for pluralizing, `Str::plural()` to be exact.

**Comment by greg0ire** [comment]
Oh I wasn't confused about the issue was, but about how you noticed it. Thanks for clarifying that.

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]
✅ if we still add this change to the next patch release.

Is the failed bc check somehow relevant to the change?

**Comment by greg0ire** [comment]
No, it has to do with https://github.com/Nyholm/roave-bc-check-docker/issues/32

**Review by derrabus — COMMENTED** [review]
That case should be added to `EnglishFunctionalTest` as well.

**Review by derrabus — APPROVED** [review]

**Comment by pimjansen** [comment]
> No, it has to do with https://github.com/Nyholm/roave-bc-check-docker/issues/32

Same my last reply on the issue there!

**Comment by greg0ire** [comment]
Thanks @kyosheek !

**Pull request merged**
