### PR TITLE
Added more uninflected words

### PR DESCRIPTION
**Pull request by ajthinking**

### CODE REVIEW

**Comment by ajthinking** [comment]
Will do, but ran into some problems as I am new to testing. Issue: https://github.com/doctrine/inflector/issues/61

**Comment by ajthinking** [comment]
Added tests, hope it is ready for merge now. 

I did find a bug on a previously present word ".*?media". For instance testing "social media" breaks this. I will not fix that atm but will fill an issue.

**Comment by HipsterJazzbo** [comment]
This should be fine to merge now, yeah?

**Comment by malarzm** [comment]
@ajthinking mind squashing the commits?

**Comment by ajthinking** [comment]
@malarzm squashed!

**Comment by malarzm** [comment]
Thanks @ajthinking!

**Pull request merged**
