### PR TITLE
Reintroduce PHP 7.1 support

### PR DESCRIPTION
**Pull request by beberlei**
Code still works on 7.1, no need to restrict it.

### CODE REVIEW

**Comment by greg0ire** [comment]
Should this target `2.1.x`? It's not really a bug is it?

**Review by greg0ire — APPROVED** [review]

**Comment by alcaeus** [comment]
I don't see a reason for bringing this back tbh. What's the reasoning behind this?

**Comment by beberlei** [comment]
@alcaeus the reason is that it still works on 7.1, DBAL 2.x still supports 7.1 and ORM also can support this because only this holds it back. Edit: All tooling supports 7.1 as well, PHPUnit, Psalm, phpcs and our coding standard.

**Review by alcaeus — CHANGES_REQUESTED** [review]
Absolutely not from my end: people can use version 1.3 if they need to run on 7.1. If you want them to be able to use the new api, introduce 7.1 support to 1.4.

**Comment by beberlei** [comment]
Replaced by #186

**Pull request closed without merging**
