### PR TITLE
Change unnecessary double quotes to single quotes

### PR DESCRIPTION
**Pull request by Bilge**

### CODE REVIEW

**Comment by Ocramius** [comment]
@Bilge thanks!

**Comment by Bilge** [comment]
That's cool, I- you know. If it's still good two years later that's how you know it's a quality PR.

**Comment by Ocramius** [comment]
@Bilge you are very welcome to do free work on your own if you want a ban also from the doctrine repositories.

**Comment by Bilge** [comment]
@Ocramius What?

**Pull request merged**
