### PR TITLE
Fix pluralisations of research and homework

### LINKED ISSUE #156: Pluralizer problem
# Laravel Version: 7.11.0
# PHP Version: 7.2.24

Description:
The output of the following code is incorrect
Str::plural('Research')

Output code: Research
The output it has to give: Researches

### PR DESCRIPTION
**Pull request by alcaeus**
Fixes #156.

### CODE REVIEW

**Comment by tomcastleman** [comment]
My issue related to #156 was with the word `weather` but it has 2 valid plurals `weather|weathers` depending on context and would be unsure which to choose!

**Comment by alcaeus** [comment]
Please create a separate issue for that if you don't want me to lose track of words. Thanks!

**Comment by GrahamCampbell** [comment]
I don't think either of these changes are correct, actually. We should regard the changes in 1.4.0 as a bug fix. The plural of research *is* research, and *not* researches.

**Comment by alcaeus** [comment]
Since I'm not a native speaker, I have to go by what I can read in various resources. It seems to me that while "researches" is a valid plural for "research", it's rarely used since research is considered uncountable.

Similarly with "homework": while there is a case for having multiple works, many homework assignments are still homework, not homeworks. I'll let other people more familiar with the nuances of the English language chime in, but we might as well consider these changes fixes of long-standing bugs.

**Comment by garrettw** [comment]
@alcaeus you would be correct. And your English is indistinguishable from that of a native speaker.

**Comment by alcaeus** [comment]
Thanks for confirming, @garrettw. Closing this PR and the associated issue. For those folks wanting to preserve the old behaviour, you can create custom rules to modify the inflector to your needs.

**Pull request closed without merging**
