### PR TITLE
Correct pluralization of axis

### PR DESCRIPTION
**Pull request by iurciuc**
Issue: https://github.com/doctrine/inflector/issues/240

[What Is the Plural of Axis?](https://www.splashlearn.com/math-vocabulary/geometry/axis-plural-axes#1-what-is-the-plural-of-axis)

### CODE REVIEW

**Comment by malarzm** [comment]
@iurciuc thanks for your PR! I'm afraid we have a hard nut to crack here as per the tests: `axes` was previously singularized to `axe` and after your change no longer is. I can't really see a way forward as fixing your bug means breaking something that worked before :/

**Comment by malarzm** [comment]
Theoretically we could fix axis -> axes and still have axes -> axe as the lib has no way of knowing what word it should singularize into. Thoughts?

**Comment by iurciuc** [comment]
In 99% of cases axes->axe will be what user expected!
To be consistent(English in this case is not so consistent) we can build a feature to provide possibility to extend the logic of this lib by a config.

**Comment by malarzm** [comment]
I think config is an overkill in this case :) Let's proceed with fixing axis -> axes but keeping axes -> axe

**Comment by iurciuc** [comment]
Fixed

**Comment by malarzm** [comment]
Thanks @iurciuc!

**Pull request merged**
