### PR TITLE
Fix raves

### LINKED ISSUE #228: Wrong singularization of "raves"
The singular of `raves` should be `rave` and not `rafe`.

### PR DESCRIPTION
**Pull request by TheBlckbird**
Closes #228

### CODE REVIEW

**Comment by derrabus** [comment]
Please add your scenario to `EnglishFunctionalTest`.

**Comment by TheBlckbird** [comment]
I will test this in two weeks, I am currently on vacation.

**Comment by TheBlckbird** [comment]
This should now be fixed

**Comment by TheBlckbird** [comment]
Why is this check failing?

**Pull request closed without merging**
