### PR TITLE
Use CodeCov instead of Scrutinizer

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These codecov reports are so annoying. :/

**Comment by greg0ire** [comment]
@GrahamCampbell we are discussing internally to see if we might switch to just status checks based on https://docs.codecov.io/docs/commit-status

**Comment by greg0ire** [comment]
Doesn't seem to work, except for the comment. @beberlei can you try copy pasting the YAML from this PR at https://codecov.io/account/gh/doctrine/yaml ? I think some changes are not taken into account until [the change is merged up](https://docs.codecov.io/docs/codecov-yaml#master-copy).

**Comment by GrahamCampbell** [comment]
Do they have a web interface for setting the config?

**Comment by GrahamCampbell** [comment]
Given that they don't actually read the one in the code, there seems to be little point keeping it in the version control.

**Comment by greg0ire** [comment]
> Do they have a web interface for setting the config?

They do, but it's global to the team, and I don't have the required permissions to create it. I'm of course not planning to keep it under version control if this works as expected.

**Comment by beberlei** [comment]
@greg0ire done

**Comment by greg0ire** [comment]
Great! Let's see…

**Comment by greg0ire** [comment]
No dice… something else might need to be done.

**Comment by greg0ire** [comment]
@beberlei I just requested installing the CodeCov Github App on Doctrine, I think that might be the missing piece. I'm ensure who receives the request, maybe it's you.

**Comment by beberlei** [comment]
@greg0ire nothing, can you link me that page to request the app?

**Comment by greg0ire** [comment]
Sure: https://github.com/apps/codecov

**Comment by beberlei** [comment]
@greg0ire done

**Comment by greg0ire** [comment]
It works!!!

**Comment by GrahamCampbell** [comment]
It seems to have reported green before the tests have even run. :trollface:

**Comment by greg0ire** [comment]
Well there was already a report for that commit, so I guess it just found it instantly and posted it here.

**Comment by greg0ire** [comment]
No report straightaway this time.

**Comment by beberlei** [comment]
<3

**Comment by greg0ire** [comment]
And now we have a report, but it says coverage not affected :facepalm:

**Comment by greg0ire** [comment]
Ah but that's normal for patch: my patch has no code. And for project, there is nothing to compare against yet.

**Comment by greg0ire** [comment]
Let me try to add some code in my patch.

**Comment by greg0ire** [comment]
:thinking: in the report, it correctly detects the line as uncovered, but it reports as "Coverage not affected", not sure why…

**Comment by greg0ire** [comment]
I just closed and reopened this PR: https://github.com/doctrine/dbal/pull/4036 It has missing test, maybe it will show up differently, since there are already reports on the DBAL.

**Comment by greg0ire** [comment]
Same weird result… I'm starting to think this has to do with informational mode, let's try to turn it off.

**Comment by greg0ire** [comment]
I filed a support request here: https://community.codecov.io/t/informational-mode-coverage-not-affected/1585

My hope for the DBAL is that it will work properly for commits that are based off commits that have a report. The PR I closed and reopened is properly too old.

**Comment by greg0ire** [comment]
Ah look!!! This PR looks good: https://github.com/doctrine/dbal/pull/4074

**Comment by greg0ire** [comment]
No answer on discourse… let's drop the dummy commits and merge this.

**Pull request merged**
