### PR TITLE
Remove countable word

### PR DESCRIPTION
**Pull request by driesvints**
The word "environment" is countable. Please see https://github.com/doctrine/inflector/pull/216#discussion_r1232174367

### CODE REVIEW

**Comment by driesvints** [comment]
The failing CI check is failing on 2.0.x as well.

**Comment by greg0ire** [comment]
I'd love to have your input on https://github.com/doctrine/inflector/issues/221 as well.

**Comment by EilifAkerjordet** [comment]
I would like to add that the same goes for the word "permission" - I see more words as well in #216 that are countable

**Comment by greg0ire** [comment]
When talking about "the environment" (as in :deciduous_tree: ), I think it's uncountable. But when talking about "an environment" it isn't, and in our jobs, it's more likely we are going to talk about the latter, so it seems fair to revert this. Should we revert other words as well, such as "permission"? Also, is there something we can do to prevent them from being added again? IIRC it's possible to add tests for this.

**Comment by driesvints** [comment]
Closing this as I don't think reverting just one word is the right approach.

**Pull request closed without merging**
