### PR TITLE
More Inflections

### PR DESCRIPTION
**Pull request by sunspikes**
Inflection for potato / potatoes, volcano / volcanoes, analysis / analyses, thesis / theses.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This would be better with tests to prove this works. :)

**Comment by sunspikes** [comment]
Thanks @GrahamCampbell, added tests.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Any chance of a tag soon?

**Pull request merged**
