### PR TITLE
Add pluralization of "larva"

### PR DESCRIPTION
**Pull request by DanJFletcher**
**What does this PR do?**

The pluralization of "larva" is "larvae". Inflector used to return "larvas" as the plural. With this PR it now returns "larvae" 👍 

**Note**

My editor cleans trailing whitespace. I can fix this PR if that's a problem - sorry :/

### CODE REVIEW

**Comment by JesseLeite** [comment]
+1, I need this for my science research app.

**Comment by DanJFletcher** [comment]
I'm guessing this repo is abandoned?

**Comment by garrettw** [comment]
Sure looks that way. I would be more than happy to fork it and merge all PRs as a public service. I've been wanting to do a bit of refactoring on this for a while anyway.

**Comment by malarzm** [comment]
I'll try to take a look at failing tests today

**Comment by alcaeus** [comment]
> I'll try to take a look at failing tests today

Should be fixed by rebasing on top of master.

**Comment by alcaeus** [comment]
@DanJFletcher could you rebase on top of master to fix build failures? Thanks!

**Comment by DanJFletcher** [comment]
@alcaeus Hey sorry, I've been bad at checking my notifications lately!

**Comment by malarzm** [comment]
Thanks a bunch @DanJFletcher!

**Comment by DanJFletcher** [comment]
@malarzm No problem - cheers!

**Pull request merged**
